version: '3.8'
services:
  web:
    container_name: itc_web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    working_dir: /var/www/html
    hostname: web
    volumes:
      - ./:/var/www/html:cached
      - ./:/var/run/php-fpm/
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: itc_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    depends_on:
      - database

  nginx:
    image: nginx:1.19.0
    container_name: itc_nginx
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html:cached
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - web

  database:
    container_name: itc_database
    image: mariadb:10.4
    ports:
      - "3308:3306"
    volumes:
      - itc-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: itc_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret

volumes:
  itc-db-data:
